"""P2.5 codegen: bake the P2.2 fill model JSON into a Rust source file.

Reads experiments/data/p22/fill_model.json (12 isotonic curves, each a 101-point
queue_frac -> P(fill) table on a uniform grid) and emits core/src/fill_tables.rs
with one `const [f64; 101]` per curve. This mirrors how PropagatorKernel::calibrated()
and calibrated_race_latency() bake fitted constants into Rust, keeping the sim
dependency-free (no runtime JSON parsing).

Run from repo root: python3 scripts/p25_gen_fill_tables.py
"""
import json
from pathlib import Path

SRC = Path("experiments/data/p22/fill_model.json")
OUT = Path("core/src/fill_tables.rs")

KEYS = [
    "bid_trade_1s", "bid_trade_10s", "bid_trade_60s",
    "bid_any_1s", "bid_any_10s", "bid_any_60s",
    "ask_trade_1s", "ask_trade_10s", "ask_trade_60s",
    "ask_any_1s", "ask_any_10s", "ask_any_60s",
]

m = json.loads(SRC.read_text())
for k in KEYS:
    x, y = m[k]["x"], m[k]["y"]
    assert len(x) == 101 and len(y) == 101, (k, len(x), len(y))
    assert abs(x[0]) < 1e-9 and abs(x[-1] - 1.0) < 1e-9, f"{k}: x grid not [0,1]"
    assert abs((x[1] - x[0]) - 0.01) < 1e-9, f"{k}: x step != 0.01"

lines = [
    "//! Calibrated fill-probability tables — GENERATED by scripts/p25_gen_fill_tables.py.",
    "//! DO NOT EDIT BY HAND. Source: experiments/data/p22/fill_model.json (P2.2 isotonic fit).",
    "//!",
    "//! Each curve is P(fill within horizon | queue_frac), isotonic (monotone",
    "//! non-increasing in queue_frac) on the uniform grid 0.00, 0.01, ..., 1.00.",
    "",
    "/// Number of grid points per curve (queue_frac 0.00..=1.00 step 0.01).",
    "pub const N: usize = 101;",
    "/// Grid step in queue-fraction units.",
    "pub const STEP: f64 = 0.01;",
    "",
]
for k in KEYS:
    vals = ", ".join(repr(float(v)) for v in m[k]["y"])
    lines.append(f"pub const {k.upper()}: [f64; N] = [{vals}];")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(KEYS)} curves x {len(m[KEYS[0]]['y'])} pts)")
